Review/metadata persistence
bdeggleston/cassandra pull request #7
Opened 2022-08-30 17:58 UTC by dcapwell

2022-08-30 17:59 UTC, dcapwell commented on src/java/org/apache/cassandra/service/accord/db/AccordUpdate.java
> +            return applies(partition == null ? null : partition.getRow(clustering));
this was a bug found while running the `multipleShards` test; can't pull a row from a null partition to check if row exists.

2022-08-30 18:02 UTC, dcapwell commented on test/distributed/org/apache/cassandra/distributed/test/accord/AccordIntegrationTest.java
> +        long deadlineNanos = nanoTime() + TimeUnit.SECONDS.toNanos(1);
trying to get tests to fail, will make this 30s

2022-08-30 18:16 UTC, maedhroz approved these changes

2022-08-31 22:01 UTC, bdeggleston requested changes

2022-08-31 22:01 UTC, bdeggleston commented on test/distributed/org/apache/cassandra/distributed/util/QueryResultUtil.java
> +        return map(input, Map.of(c1, (Function<Object, Object>) c1Fn,
We should just accept a map and call with `Map.of` in the test, instead of having a fixed number of conversion functions

2022-09-01 00:53 UTC, dcapwell commented on test/distributed/org/apache/cassandra/distributed/util/QueryResultUtil.java
> +        return map(input, Map.of(c1, (Function<Object, Object>) c1Fn,
migrated

2022-09-01 16:29 UTC, bdeggleston approved these changes
+1

2022-09-01 16:30 UTC, merged